In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
column_names = [
    "CrimeRate",  # The per capita crime rate by town. lower housing values
    "ResidentialLandZoned", # The proportion of residential land zoned for lots over 25,000 sq.ft.
    "IndustrialLandUse", # The proportion of non-retail business acres per town.
    "CharlesRiver", # Charles River dummy variable (1 if tract bounds river; 0 otherwise)
    "NitrixOxide", # Nitric oxides concentration (parts per 10 million)
    "AvgRoomPerDwelling", # The average number of rooms per dwelling
    "HousingAge", # The proportion of owner-occupied units built prior to 1940
    "DistanceToWork", # Weighted distances to five Boston employment centres
    "HighwayAccess", # Index of accessibility to radial highways
    "PropertyTaxRate", # Full-value property-tax rate per $10,000
    "Pupil-TeacherRatio", # The pupil-teacher ratio by town
    "B", # 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
    "LowSocioEcomic", # The percentage of lower status of the population
    "Value", # Median value of owner-occupied homes in $1000s
]
df = pd.read_csv("data/housing.csv", sep=r"\s+", header=None, names=column_names)

In [3]:
df.head(2)

,CrimeRate,ResidentialLandZoned,IndustrialLandUse,CharlesRiver,NitrixOxide,AvgRoomPerDwelling,HousingAge,DistanceToWork,HighwayAccess,PropertyTaxRate,Pupil-TeacherRatio,B,LowSocioEcomic,Value
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [1]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import mlflow
from mlflow.entities import ViewType
from mlflow.tracking import MlflowClient
client = MlflowClient()

mlflow.set_tracking_uri("http://localhost:5020")
mlflow.set_experiment("Boston Model Experiment")
# mlflow.set_registry_uri("sqlite:///mlflow_registry.db")

<Experiment: artifact_location='mlflow-artifacts:/417350048653659120', creation_time=1756917308481, experiment_id='417350048653659120', last_update_time=1756917308481, lifecycle_stage='active', name='Boston Model Experiment', tags={}>

In [6]:
feature_cols = ["CrimeRate", "ResidentialLandZoned", "IndustrialLandUse", "CharlesRiver", "NitrixOxide", "AvgRoomPerDwelling", "HousingAge", "DistanceToWork", "HighwayAccess", "PropertyTaxRate", "Pupil-TeacherRatio", "B", "LowSocioEcomic"]
X = df[feature_cols]
y = df['Value']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
mlflow.start_run(run_name="XGBRegressor Run")

xgb_model = XGBRegressor(n_estimators=150, max_depth=5, learning_rate=0.05, random_state=42)
xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5

mlflow.log_metric("rmse", rmse)
mlflow.xgboost.log_model(xgb_model, "xgbr_model")

model_name = "XGBRegressor Model"
model_uri = f"runs:/{mlflow.active_run().info.run_id}/xgbr_model"
mlflow.register_model(model_uri, model_name)

mlflow.end_run()

2025/09/04 23:09:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\ProgramData\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [23:09:22] WARNING: C:\b\abs_90_bwj_86a\croot\xgboost-split_1724073762025\work\src\c_api\c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  warnings.warn(smsg, UserWarning)
2025/09/04 23:09:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/09/04 23:09:30 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/09/04 23:09:30 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
INFO  [alembic.runtime.migration] Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
INFO  [alembic.runtime.migration] Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
INFO  [alembic.runtime.migration] Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
INFO  [alembic.runtime.migration] Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
INFO  [alembic.runtime.migration] Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
INFO  [alembic.runtime.migration] Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
INFO  [alembic.runtime.migration] Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
INFO  [alembic.runtime.migration] Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
INFO  [alembic.runtime.migration] Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
Successfully registered model 'XGBRegressor Model'.
2025/09/04 23:09:30 WARNING mlflow.tracking._model_registry.fluent: Run with id c17cc64c833140929519e5e7ab80e20b has no artifacts at artifact path 'xgbr_model', registering model based on models:/m-6b7993631a254102ac8b3b5371b53d77 instead
Created version '1' of model 'XGBRegressor Model'.

🏃 View run XGBRegressor Run at: http://localhost:5020/#/experiments/417350048653659120/runs/c17cc64c833140929519e5e7ab80e20b
🧪 View experiment at: http://localhost:5020/#/experiments/417350048653659120

1. A logged model is a model artifact saved during an MLflow run. It is stored in the MLflow tracking server or a specified artifact storage location. Logged models are primarily used for experimentation and tracking purposes.
- Purpose: Captures the model, its parameters, metrics, and artifacts during training.
- Storage: Saved as part of an MLflow run under the artifacts section.
- Access: Can be loaded using the mlflow.<model_flavor>.load_model() method with a run-relative path (e.g., runs:/<run_id>/<model_path>).
- Use Case: Ideal for experimentation, debugging, and intermediate model evaluation.

2. A registered model is a model that has been added to the MLflow Model Registry. It provides a centralized system for managing models across their lifecycle, including versioning, staging, and deployment.

- Purpose: Enables collaborative model management with features like versioning, aliases, and metadata tagging.
- Storage: Stored in the Model Registry with a unique name and associated versions.
- Access: Can be loaded using a model URI (e.g., models:/<model_name>/<version> or models:/<model_name>@<alias>).
- Use Case: Suitable for production workflows, deployment, and governance.

In [ ]:
# Load registered model and make predictions
loaded_model = mlflow.pyfunc.load_model(model_uri)
loaded_model.predict(X_test)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

In [2]:

# Exact name match
for exp in mlflow.search_experiments(
        view_type=ViewType.ALL,
        filter_string="name = 'Boston Model Experiment'"):
    print(exp.experiment_id, exp.name, exp.lifecycle_stage)

417350048653659120 Boston Model Experiment active

In [2]:
for exp in mlflow.search_experiments(
        filter_string="name LIKE '%Boston%'"):
    print(exp.experiment_id, exp.name)

417350048653659120 Boston Model Experiment

In [3]:
exp = mlflow.get_experiment_by_name("Boston Model Experiment")
if exp is None:
    raise ValueError(f"Experiment not found: Boston Model Experiment")
runs = mlflow.search_runs(
    experiment_ids=[exp.experiment_id],
    filter_string="attributes.status = 'FINISHED'",
    order_by=["start_time DESC"],
    max_results=3,
)
if runs.empty:
    raise RuntimeError("No finished runs found.")
run_id = runs.iloc[0]["run_id"]

In [4]:
runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.rmse,tags.mlflow.user,tags.mlflow.source.type,tags.mlflow.source.name,tags.mlflow.runName
0,c17cc64c833140929519e5e7ab80e20b,417350048653659120,FINISHED,mlflow-artifacts:/417350048653659120/c17cc64c8...,2025-09-05 06:09:20.038000+00:00,2025-09-05 06:09:30.612000+00:00,2.421340,mamma,LOCAL,c:\ProgramData\anaconda3\Lib\site-packages\ipy...,XGBRegressor Run
1,d2de8e82dfcf4bb1ac6dddcc5f3a74d9,417350048653659120,FINISHED,mlflow-artifacts:/417350048653659120/d2de8e82d...,2025-09-03 16:43:41.177000+00:00,2025-09-03 16:43:46.637000+00:00,2.659466,mamma,LOCAL,c:\ProgramData\anaconda3\Lib\site-packages\ipy...,XGBRegressor Run
2,5e803f75d4564e1abf300ce9fac37bfc,417350048653659120,FINISHED,mlflow-artifacts:/417350048653659120/5e803f75d...,2025-09-03 16:42:41.847000+00:00,2025-09-03 16:42:51.456000+00:00,2.659466,mamma,LOCAL,c:\ProgramData\anaconda3\Lib\site-packages\ipy...,XGBRegressor Run

In [ ]:
import mlflow
from mlflow.entities import ViewType
from mlflow.tracking import MlflowClient
client = MlflowClient()

mlflow.set_tracking_uri("http://localhost:5020")
mlflow.set_experiment("Boston Model Experiment")
from urllib.parse import urlparse, unquote
run = client.get_run(run_id)
model = mlflow.pyfunc.load_model(f"runs:/d2de8e82dfcf4bb1ac6dddcc5f3a74d9/model")
for a in client.list_artifacts(run_id):
    print("ARTIFACT:", a.path)
    art_uri = run.info.artifact_uri               # e.g., file:///C:/.../mlruns/<exp>/<run>/artifacts
p = urlparse(art_uri)
if p.scheme != "file":
    raise RuntimeError(f"Artifact store is not local file:// (got {art_uri})")